"power_share-Power Share":
"campaigns-Campaigns":
"listen-Listen":
"chat-Chat":
"pipeline-Pipeline":
"delivery-Delivery":
"configure-Configure":
 configure_social-Social:
 configure_mobile-Customers:
 configure_company-Company:
 configure_listen-Listen:
 configure_location-In Location:
"account-Account":
 account_settings-Settings:
 account_payments-Payments:
"alerts-Alerts":
"client-Teams and Roles":
 client_roles-Roles:
 client_users-Users:
 client_tenants-Tenants:
"pipeline_delivery-Pipeline Delivery":
"pipeline_marketting-Pipeline Marketting":