##
##
port: 3010
user: inquirly
address: 0.0.0.0
group: inquirly
pid: "/var/www/apps/inquirly/current/tmp/pids/thin.pid"
timeout: 300
wait: 30
log: "/var/www/apps/inquirly/current/log/thin.log"
#debug: true
max_conns: 1024
require: []
environment: production
max_persistent_conns: 512
servers: 2
onebyone: true
#trace: yes
#threaded: true
no-epoll: true
daemonize: true
socket: "/var/www/apps/inquirly/current/tmp/sockets/thin.sock"
chdir: "/var/www/apps/inquirly/current"
tag: thin_v2
